// Generated by Combe/JS Bootstrap Compiler

var extend = require('./util').extend;
var BaseParser = require('./base_parser');
var Range = require('./range');

var CombeASTTranslator = module.exports = function () {
  BaseParser.call(this);
};

extend((CombeASTTranslator.prototype = Object.create(BaseParser.prototype)), {

'recur': function () {
var result;
return this._apply((function () {return this._concat((function () {return this._destructure((function () {result = this._apply(this.transform);}));}), (function () {return ( result
  );}));}));
},

'transform': function () {
var name, rules, args, vars, expr, exprs, jsExpr, argExprs, jsCode, leftExpr, rightExpr, string, number;
return this._apply((function () {return this._choice((function () {return this._concat((function () {return this._concat('Grammar', (function () {name = this._apply((function () {return this._apply(this.anything);}));}), (function () {return this._destructure((function () {rules = this._apply((function () {return this._repeat(this.recur);}));}));}));}), (function () {return ( ["// Generated by Combe/JS Compiler\n",
            "\n",
            "var extend = require('./util').extend;\n",
            "var BaseParser = require('./base_parser');\n",
            "var Range = require('./range');\n",
            "\n",
            "var ", name, " = module.exports = function () {\n",
            "  BaseParser.call(this);\n",
            "};\n",
            "\n",
            "extend((", name, ".prototype = Object.create(BaseParser.prototype)), {\n",
            "\n",
            rules.interpolate(',\n\n'), '\n\n',
            '});\n']
    
    );}));}),
(function () {return this._concat((function () {return this._concat('Rule', (function () {name = this._apply((function () {return this._apply(this.anything);}));}), (function () {args = this._apply((function () {return this._apply(this.anything);}));}), (function () {vars = this._apply((function () {return this._apply(this.anything);}));}), (function () {expr = this._apply(this.recur);}));}), (function () {return ( [(name.isReserved() ? name.quote() : name), 
              ': function (', args.interpolate(', '), ') {\n',
            (vars.isEmpty() ? '' : ['var ', vars.interpolate(', '), ';\n']),
            'return this._apply(', expr, ');\n',
            '}']
    
    );}));}),
(function () {return this._concat((function () {return this._concat('Choice', (function () {exprs = this._apply((function () {return this._repeat1(this.recur);}));}));}), (function () {return ( ['(function () {return this._choice(', exprs.interpolate(',\n'), ');})']
    
    );}));}),
(function () {return this._concat((function () {return this._concat('Concat', (function () {exprs = this._apply((function () {return this._repeat1(this.recur);}));}));}), (function () {return ( ['(function () {return this._concat(', exprs.interpolate(',\n'), ');})']
    
    );}));}),
(function () {return this._concat((function () {return this._concat('Action', (function () {jsExpr = this._apply(this.recur);}));}), (function () {return ( jsExpr
    
    );}));}),
(function () {return this._concat((function () {return this._concat('Bind', (function () {name = this._apply((function () {return this._apply(this.anything);}));}), (function () {expr = this._apply(this.recur);}));}), (function () {return ( ['(function () {return (', name, ' = this._apply(', expr, '));})']
    
    );}));}),
(function () {return this._concat((function () {return this._concat('Not', (function () {expr = this._apply(this.recur);}));}), (function () {return ( ['(function () {return this._not(', expr, ');})']
    
    );}));}),
(function () {return this._concat((function () {return this._concat('Lookahead', (function () {expr = this._apply(this.recur);}));}), (function () {return ( ['(function () {return this._lookahead(', expr, ');})']
    
    );}));}),
(function () {return this._concat((function () {return this._concat('Repeat', (function () {expr = this._apply(this.recur);}));}), (function () {return ( ['(function () {return this._repeat(', expr, ');})']
    
    );}));}),
(function () {return this._concat((function () {return this._concat('Repeat1', (function () {expr = this._apply(this.recur);}));}), (function () {return ( ['(function () {return this._repeat1(', expr, ');})']
    
    );}));}),
(function () {return this._concat((function () {return this._concat('Optional', (function () {expr = this._apply(this.recur);}));}), (function () {return ( ['(function () {return this._optional(', expr, ');})']
    
    );}));}),
(function () {return this._concat((function () {return this._concat('Token', (function () {expr = this._apply(this.recur);}));}), (function () {return ( ['(function () {return this.token(', expr, ');})']
    
    );}));}),
(function () {return this._concat((function () {return this._concat('Predicate', (function () {jsExpr = this._apply(this.recur);}));}), (function () {return ( ['(function () {return this._predicate(', expr, ');})']
    
    );}));}),
(function () {return this._concat('Apply', (function () {expr = this._apply(this.recur);}), (function () {return this._choice((function () {return this._concat((function () {return this._destructure((function () {argExprs = this._apply((function () {return this._repeat(this.recur);}));}));}), (function () {return ( ['(function () {return this._apply(', expr, ', ', 
                argExprs.interpolate(', '), ');})']
      );}));}),
(function () {return ( ['(function () {return this._apply(', expr, ');})']
      );}));}));}),
(function () {return this._concat((function () {return this._concat('ImmediateAction', (function () {return this._destructure((function () {return this._concat('JSFunction', (function () {jsCode = this._apply((function () {return this._apply(this.anything);}));}));}));}));}), (function () {return ( ['(function () {', jsCode, '}).call(this)']
    
    );}));}),
(function () {return this._concat((function () {return this._concat('ImmediateAction', (function () {return this._destructure((function () {return this._concat('JSExpr', (function () {jsCode = this._apply((function () {return this._apply(this.anything);}));}));}));}));}), (function () {return ( ['(', jsCode, ')']
    
    );}));}),
(function () {return this._concat((function () {return this._concat('Destructure', (function () {expr = this._apply(this.recur);}));}), (function () {return ( ['(function () {return this._destructure(', expr, ');})']
    
    );}));}),
(function () {return this._concat((function () {return this._concat('Range', (function () {leftExpr = this._apply(this.recur);}), (function () {rightExpr = this._apply(this.recur);}));}), (function () {return ( ['(new Range(', leftExpr, ', ', rightExpr, '))']
    
    );}));}),
(function () {return this._concat('Infinity', (function () {return ( 'Infinity'
    
    );}));}),
(function () {return this._concat((function () {return this._concat('String', (function () {string = this._apply((function () {return this._apply(this.anything);}));}));}), (function () {return ( string
    
    );}));}),
(function () {return this._concat((function () {return this._concat('Number', (function () {number = this._apply((function () {return this._apply(this.anything);}));}));}), (function () {return ( number
    
    );}));}),
(function () {return this._concat((function () {return this._concat('Variable', (function () {name = this._apply((function () {return this._apply(this.anything);}));}));}), (function () {return ( name
    
    );}));}),
(function () {return this._concat((function () {return this._concat('Property', (function () {name = this._apply((function () {return this._apply(this.anything);}));}));}), (function () {
          if (name.isReserved()) {
            return 'this[' + name.quote() + ']';
          } else {
            return 'this.' + name;
          }
        }));}),
(function () {return this._concat((function () {return this._concat('JSFunction', (function () {jsCode = this._apply((function () {return this._apply(this.anything);}));}));}), (function () {return ( ['(function () {', jsCode, '})']
    
    );}));}),
(function () {return this._concat((function () {return this._concat('JSExpr', (function () {jsCode = this._apply((function () {return this._apply(this.anything);}));}));}), (function () {return ( ['(function () {return (', jsCode, ');})']
  );}));}));}));
}

});
