// Generated by Combe/JS Compiler

var extend = require('./util').extend;
var BaseParser = require('./base_parser');
var Range = require('./range');

var CombeASTTranslator = module.exports = function () {
  BaseParser.call(this);
};

extend((CombeASTTranslator.prototype = Object.create(BaseParser.prototype)), {

recur: function () {
var result;
return this._apply((function () {return this._concat((function () {return this._destructure((function () {return (result = this._apply(this.transform));}));}),
(function () {return ( result
  );}));}));
},

transform: function () {
var name, rules, args, vars, expr, exprs, jsExpr, argExprs, jsCode, leftExpr, rightExpr, string, number;
return this._apply((function () {return this._choice((function () {return this._concat('Grammar',
(function () {return (name = this._apply((function () {return this._apply(this.anything);})));}),
(function () {return this._destructure((function () {return (rules = this._apply((function () {return this._repeat(this.recur);})));}));}),
(function () {return ( ["// Generated by Combe/JS Compiler\n",
            "\n",
            "var extend = require('./util').extend;\n",
            "var BaseParser = require('./base_parser');\n",
            "var Range = require('./range');\n",
            "\n",
            "var ", name, " = module.exports = function () {\n",
            "  BaseParser.call(this);\n",
            "};\n",
            "\n",
            "extend((", name, ".prototype = Object.create(BaseParser.prototype)), {\n",
            "\n",
            rules.interpolate(',\n\n'), '\n\n',
            '});\n']
    
    );}));}),
(function () {return this._concat('Rule',
(function () {return (name = this._apply((function () {return this._apply(this.anything);})));}),
(function () {return (args = this._apply((function () {return this._apply(this.anything);})));}),
(function () {return (vars = this._apply((function () {return this._apply(this.anything);})));}),
(function () {return (expr = this._apply(this.recur));}),
(function () {return ( [(name.isReserved() ? name.quote() : name), 
              ': function (', args.interpolate(', '), ') {\n',
            (vars.isEmpty() ? '' : ['var ', vars.interpolate(', '), ';\n']),
            'return this._apply(', expr, ');\n',
            '}']
    
    );}));}),
(function () {return this._concat('Choice',
(function () {return (exprs = this._apply((function () {return this._repeat1(this.recur);})));}),
(function () {return ( ['(function () {return this._choice(', exprs.interpolate(',\n'), ');})']
    
    );}));}),
(function () {return this._concat('Concat',
(function () {return (exprs = this._apply((function () {return this._repeat1(this.recur);})));}),
(function () {return ( ['(function () {return this._concat(', exprs.interpolate(',\n'), ');})']
    
    );}));}),
(function () {return this._concat('Action',
(function () {return (jsExpr = this._apply(this.recur));}),
(function () {return ( jsExpr
    
    );}));}),
(function () {return this._concat('Bind',
(function () {return (name = this._apply((function () {return this._apply(this.anything);})));}),
(function () {return (expr = this._apply(this.recur));}),
(function () {return ( ['(function () {return (', name, ' = this._apply(', expr, '));})']
    
    );}));}),
(function () {return this._concat('Not',
(function () {return (expr = this._apply(this.recur));}),
(function () {return ( ['(function () {return this._not(', expr, ');})']
    
    );}));}),
(function () {return this._concat('Lookahead',
(function () {return (expr = this._apply(this.recur));}),
(function () {return ( ['(function () {return this._lookahead(', expr, ');})']
    
    );}));}),
(function () {return this._concat('Repeat',
(function () {return (expr = this._apply(this.recur));}),
(function () {return ( ['(function () {return this._repeat(', expr, ');})']
    
    );}));}),
(function () {return this._concat('Repeat1',
(function () {return (expr = this._apply(this.recur));}),
(function () {return ( ['(function () {return this._repeat1(', expr, ');})']
    
    );}));}),
(function () {return this._concat('Optional',
(function () {return (expr = this._apply(this.recur));}),
(function () {return ( ['(function () {return this._optional(', expr, ');})']
    
    );}));}),
(function () {return this._concat('Token',
(function () {return (expr = this._apply(this.recur));}),
(function () {return ( ['(function () {return this.token(', expr, ');})']
    
    );}));}),
(function () {return this._concat('Predicate',
(function () {return (jsExpr = this._apply(this.recur));}),
(function () {return ( ['(function () {return this._predicate(', expr, ');})']
    
    );}));}),
(function () {return this._concat('Apply',
(function () {return (expr = this._apply(this.recur));}),
(function () {return this._choice((function () {return this._concat((function () {return this._destructure((function () {return (argExprs = this._apply((function () {return this._repeat(this.recur);})));}));}),
(function () {return ( ['(function () {return this._apply(', expr, ', ', 
                argExprs.interpolate(', '), ');})']
      );}));}),
(function () {return ( ['(function () {return this._apply(', expr, ');})']
      );}));}));}),
(function () {return this._concat('ImmediateAction',
(function () {return this._destructure((function () {return this._concat('JSFunction',
(function () {return (jsCode = this._apply((function () {return this._apply(this.anything);})));}));}));}),
(function () {return ( ['(function () {', jsCode, '}).call(this)']
    
    );}));}),
(function () {return this._concat('ImmediateAction',
(function () {return this._destructure((function () {return this._concat('JSExpr',
(function () {return (jsCode = this._apply((function () {return this._apply(this.anything);})));}));}));}),
(function () {return ( ['(', jsCode, ')']
    
    );}));}),
(function () {return this._concat('Destructure',
(function () {return (expr = this._apply(this.recur));}),
(function () {return ( ['(function () {return this._destructure(', expr, ');})']
    
    );}));}),
(function () {return this._concat('Range',
(function () {return (leftExpr = this._apply(this.recur));}),
(function () {return (rightExpr = this._apply(this.recur));}),
(function () {return ( ['(new Range(', leftExpr, ', ', rightExpr, '))']
    
    );}));}),
(function () {return this._concat('Infinity',
(function () {return ( 'Infinity'
    
    );}));}),
(function () {return this._concat('String',
(function () {return (string = this._apply((function () {return this._apply(this.anything);})));}),
(function () {return ( string
    
    );}));}),
(function () {return this._concat('Number',
(function () {return (number = this._apply((function () {return this._apply(this.anything);})));}),
(function () {return ( number
    
    );}));}),
(function () {return this._concat('Variable',
(function () {return (name = this._apply((function () {return this._apply(this.anything);})));}),
(function () {return ( name
    
    );}));}),
(function () {return this._concat('Property',
(function () {return (name = this._apply((function () {return this._apply(this.anything);})));}),
(function () {
          if (name.isReserved()) {
            return 'this[' + name.quote() + ']';
          } else {
            return 'this.' + name;
          }
        }));}),
(function () {return this._concat('JSFunction',
(function () {return (jsCode = this._apply((function () {return this._apply(this.anything);})));}),
(function () {return ( ['(function () {', jsCode, '})']
    
    );}));}),
(function () {return this._concat('JSExpr',
(function () {return (jsCode = this._apply((function () {return this._apply(this.anything);})));}),
(function () {return ( ['(function () {return (', jsCode, ');})']
  );}));}));}));
}

});
