// Generated by Combe/JS Compiler

var extend = require('./util').extend;
var ParentParser = (require('./base_parser'));
var Range = require('./range');

var CombeASTChoiceConcatOptimization = module.exports = function () {
  ParentParser.call(this);
};

extend((CombeASTChoiceConcatOptimization.prototype = Object.create(ParentParser.prototype)), {

recur: function () {
var result;
return this._apply((function () {return this._concat((function () {return this._destructure((function () {return (result = this._apply(this.transform));}));}),
(function () {return ( result
  );}));}));
},

transform: function () {
var name, parent, rules, jsCode, args, vars, expr, exprs, jsExpr, argExprs, leftExpr, rightExpr, string, number;
return this._apply((function () {return this._choice((function () {return this._concat('Grammar',
(function () {return (name = this._apply((function () {return this._apply(this.anything);})));}),
(function () {return (parent = this._apply(this.recur));}),
(function () {return this._destructure((function () {return (rules = this._apply((function () {return this._repeat(this.recur);})));}));}),
(function () {return ( ['Grammar', name, parent, rules]
    
    );}));}),
(function () {return this._concat('DefaultParent',
(function () {return ( ['DefaultParent']
    
    );}));}),
(function () {return this._concat('Parent',
(function () {return this._destructure((function () {return this._concat('JSExpr',
(function () {return (jsCode = this._apply((function () {return this._apply(this.anything);})));}));}));}),
(function () {return ( ['Parent', ['JSExpr', jsCode]]
    );}));}),
(function () {return this._concat('Parent',
(function () {return this._destructure('DefaultParent');}),
(function () {return ( ['Parent', ['DefaultParent']]
    
    );}));}),
(function () {return this._concat('Rule',
(function () {return (name = this._apply((function () {return this._apply(this.anything);})));}),
(function () {return (args = this._apply((function () {return this._apply(this.anything);})));}),
(function () {return (vars = this._apply((function () {return this._apply(this.anything);})));}),
(function () {return (expr = this._apply(this.recur));}),
(function () {return ( ['Rule', name, args, vars, expr]
    
    );}));}),
(function () {return this._concat('Choice',
(function () {return (exprs = this._apply((function () {return this._repeat1((function () {return this._concat((function () {return (expr = this._apply(this.recur));}),
(function () {
          if (expr[0] === 'Choice') {
            return expr.slice(1);
          } else {
            return [expr];
          }
        }));}));})));}),
(function () {return ( ['Choice'].concat(exprs.flatten1())
    
    );}));}),
(function () {return this._concat('Concat',
(function () {return (exprs = this._apply((function () {return this._repeat1((function () {return this._concat((function () {return (expr = this._apply(this.recur));}),
(function () {
          if (expr[0] === 'Concat') {
            return expr.slice(1);
          } else {
            return [expr];
          }
        }));}));})));}),
(function () {return ( ['Concat'].concat(exprs.flatten1())
    
    );}));}),
(function () {return this._concat('Action',
(function () {return (jsExpr = this._apply(this.recur));}),
(function () {return ( ['Action', jsExpr]
    
    );}));}),
(function () {return this._concat('Bind',
(function () {return (name = this._apply((function () {return this._apply(this.anything);})));}),
(function () {return (expr = this._apply(this.recur));}),
(function () {return ( ['Bind', name, expr]
    
    );}));}),
(function () {return this._concat('Not',
(function () {return (expr = this._apply(this.recur));}),
(function () {return ( ['Not', expr]
    
    );}));}),
(function () {return this._concat('Lookahead',
(function () {return (expr = this._apply(this.recur));}),
(function () {return ( ['Lookahead', expr]
    
    );}));}),
(function () {return this._concat('Repeat',
(function () {return (expr = this._apply(this.recur));}),
(function () {return ( ['Repeat', expr]
    
    );}));}),
(function () {return this._concat('Repeat1',
(function () {return (expr = this._apply(this.recur));}),
(function () {return ( ['Repeat1', expr]
    
    );}));}),
(function () {return this._concat('Optional',
(function () {return (expr = this._apply(this.recur));}),
(function () {return ( ['Optional', expr]
    
    );}));}),
(function () {return this._concat('Token',
(function () {return (expr = this._apply(this.recur));}),
(function () {return ( ['Token', expr]
    
    );}));}),
(function () {return this._concat('Predicate',
(function () {return (jsExpr = this._apply(this.recur));}),
(function () {return ( ['Predicate', jsExpr]
    
    );}));}),
(function () {return this._concat('Apply',
(function () {return (expr = this._apply(this.recur));}),
(function () {return this._destructure((function () {return (argExprs = this._apply((function () {return this._repeat(this.recur);})));}));}),
(function () {return ( ['Apply', expr, argExprs]
                         
    );}));}),
(function () {return this._concat('Apply',
(function () {return (expr = this._apply(this.recur));}),
(function () {return ( ['Apply', expr]
    
    );}));}),
(function () {return this._concat('ImmediateAction',
(function () {return (jsExpr = this._apply(this.recur));}),
(function () {return ( ['ImmediateAction', jsExpr]
    
    );}));}),
(function () {return this._concat('Destructure',
(function () {return (expr = this._apply(this.recur));}),
(function () {return ( ['Destructure', expr]
    
    );}));}),
(function () {return this._concat('Range',
(function () {return (leftExpr = this._apply(this.recur));}),
(function () {return (rightExpr = this._apply(this.recur));}),
(function () {return ( ['Range', leftExpr, rightExpr]
    
    );}));}),
(function () {return this._concat('Infinity',
(function () {return ( ['Infinity']
    
    );}));}),
(function () {return this._concat('String',
(function () {return (string = this._apply((function () {return this._apply(this.anything);})));}),
(function () {return ( ['String', string]
    
    );}));}),
(function () {return this._concat('Number',
(function () {return (number = this._apply((function () {return this._apply(this.anything);})));}),
(function () {return ( ['Number', number]
    
    );}));}),
(function () {return this._concat('Variable',
(function () {return (name = this._apply((function () {return this._apply(this.anything);})));}),
(function () {return ( ['Variable', name]
    
    );}));}),
(function () {return this._concat('Property',
(function () {return (name = this._apply((function () {return this._apply(this.anything);})));}),
(function () {return ( ['Property', name]
    
    );}));}),
(function () {return this._concat('JSFunction',
(function () {return (jsCode = this._apply((function () {return this._apply(this.anything);})));}),
(function () {return ( ['JSFunction', jsCode]
    
    );}));}),
(function () {return this._concat('JSExpr',
(function () {return (jsCode = this._apply((function () {return this._apply(this.anything);})));}),
(function () {return ( ['JSExpr', jsCode]
  );}));}));}));
}

});
