// Generated by Combe/JS Compiler

var util = require('./util');
var Range = require('./range');

// Header ->

  var Token = require('./token');
  var BaseTextParser = require('./base_text_parser');

// <- Header

var ParentParser = (BaseTextParser);

var JSLexer = module.exports = function () {
  ParentParser.call(this);
};

util.extend((JSLexer.prototype = Object.create(ParentParser.prototype)), {

token: function (type, tags, value) {
return this._apply((function () {
      var endPosition = this.input.position;
      var token = new Token({
        type: type,
        tags: tags,
        value: value,
        startPosition: this.tokenStartPosition,
        endPosition: endPosition,
        input: this.input.current.$string,
        previousToken: this.lastToken
      });
      // Todo: change input to source on tokens
      
      if (!token.is('whitespace')) {
        for (var t = this.lastToken; t.is('whitespace'); t = t.previousToken) {
          if (t.is('newline')) {
            token.precededByNewline = true;
            break;
          }
        }
      }
      
      if (this.lastToken != null) {
        this.lastToken.nextToken = token;
      }
      this.lastToken = token;
      
      this.tokenStartPosition = endPosition;
      
      return token;
    }));
},

nextToken: function () {
return this._apply((function () {return this._concat(this.whitespace,
(function () {return this._choice(this.identifierName,
this.number,
this.assignmentOperator,
this.punctuation,
this.string,
(function () {return this._concat((function () {return this._lookahead((function () {return this._choice(this.division,
this.regex);}));}),
(function () {
        this.lastToken.endPosition = this.lastToken.startPosition;
        this.lastToken.type = 'unknown';
        this.lastToken.tags = [];
        this.lastToken.value = undefined;
        return this.lastToken;
      }));}));}));}));
},

resetToAfterToken: function (token) {
return this._apply((function () {
      this.lastToken = token;
      this.tokenStartPosition = this.input.position = token.endPosition;
      token.nextToken = null;
    }));
},

resetToBeforeToken: function (token) {
return this._apply((function () {
      if (token.previousToken) {
        this.resetToAfterToken(token.previousToken)
      } else {
        this.lastToken = null;
        this.tokenStartPosition = this.input.position = 0;
      }
    }));
},

sourceChar: function () {
return this._apply(this.char);
},

identifierName: function () {
var text;
return this._apply((function () {return this._concat((function () {return (text = this._apply((function () {return this._apply(this.matchedInput, (function () {return this._concat(this.idFirstChar,
(function () {return this._repeat(this.idChar);}));}));})));}),
(function () {return this._choice((function () {return this._concat((function () {return this._predicate((function () {return (text === 'null');}));}),
(function () {return this._apply(this.token, 'null', (['identifierName']), (null));}));}),
(function () {return this._concat((function () {return this._predicate((function () {return (text === 'true');}));}),
(function () {return this._apply(this.token, 'boolean', (['true', 'identifierName']), (true));}));}),
(function () {return this._concat((function () {return this._predicate((function () {return (text === 'false');}));}),
(function () {return this._apply(this.token, 'boolean', (['false', 'identifierName']), (false));}));}),
(function () {return this._concat((function () {return this._predicate((function () {return (text.isKeyword(text));}));}),
(function () {return this._apply(this.token, text, (['keyword', 'reservedWord', 'identifierName']));}));}),
(function () {return this._concat((function () {return this._predicate((function () {return (text.isFutureReservedWord(text));}));}),
(function () {return this._apply(this.token, 'futureReservedWord', (['reservedWord', 'identifierName']));}));}),
(function () {return this._apply(this.extendedIdentifier, text);}),
(function () {return this._apply(this.token, 'identifier', (['identifierName']), text);}));}));}));
},

extendedIdentifier: function (text) {
return this._apply(this.fail);
},

idFirstChar: function () {
return this._apply((function () {return this._apply(this.char, (new Range('a', 'z')), (new Range('A', 'Z')), '_', '$');}));
},

idChar: function () {
return this._apply((function () {return this._apply(this.char, (new Range('a', 'z')), (new Range('A', 'Z')), '_', '$', (new Range('0', '9')));}));
},

punctuation: function () {
var text;
return this._apply((function () {return this._concat((function () {return (text = this._apply((function () {return this._choice('{',
'}',
'(',
')',
'[',
']',
(function () {return this._concat('.',
(function () {return this._not(this.digit);}));}),
';',
',',
'<',
'>',
'<=',
'>=',
'===',
'!==',
'==',
'!=',
'+',
'-',
'*',
'%',
'&',
'|',
'^',
'!',
'~',
'&&',
'||',
'?',
':',
'++',
'--',
'<<',
'>>',
'>>>');})));}),
(function () {return this._apply(this.token, text, (['punctuation']));}));}));
},

assignmentOperator: function () {
var op, text;
return this._apply((function () {return this._concat((function () {return (text = this._apply((function () {return this._choice((function () {return this._concat((function () {return (op = this._apply('='));}),
(function () {return this._not('=');}),
(function () {return ( op);}));}),
'+=',
'-=',
'*=',
'%=',
'&=',
'|=',
'^=',
'<<=',
'>>>=',
'>>=');})));}),
(function () {return this._apply(this.token, text, (['punctuation', 'assignmentOperator']));}));}));
},

division: function () {
var text;
return this._apply((function () {return this._concat((function () {return (text = this._apply((function () {return this._choice('/',
'/=');})));}),
(function () {return this._apply(this.token, text, (['punctuation', 'division']));}));}));
},

number: function () {
return this._apply((function () {return this._choice(this.decimal,
this.hexInteger);}));
},

decimal: function () {
var text;
return this._apply((function () {return this._concat((function () {return (text = this._apply((function () {return this._apply(this.matchedInput, (function () {return this._choice((function () {return this._concat(this.integer,
(function () {return this._optional((function () {return this._concat('.',
(function () {return this._repeat(this.digit);}));}));}),
(function () {return this._optional((function () {return this._concat((function () {return this._choice('e',
'E');}),
(function () {return this._choice('+',
'-',
this.nothing);}),
(function () {return this._repeat1(this.digit);}));}));}));}),
(function () {return this._concat('.',
(function () {return this._repeat1(this.digit);}),
(function () {return this._optional((function () {return this._concat((function () {return this._choice('e',
'E');}),
(function () {return this._choice('+',
'-',
this.nothing);}),
(function () {return this._repeat1(this.digit);}));}));}));}));}));})));}),
(function () {return this._not(this.idChar);}),
(function () {return this._apply(this.token, 'number', (['decimal']), (parseFloat(text)));}));}));
},

integer: function () {
return this._apply((function () {return this._concat((function () {return this._apply(this.char, (new Range('1', '9')));}),
(function () {return this._repeat(this.digit);}));}));
},

digit: function () {
return this._apply((function () {return this._apply(this.char, (new Range('0', '9')));}));
},

hexInteger: function () {
var text;
return this._apply((function () {return this._concat((function () {return this._choice('0x',
'0X');}),
(function () {return (text = this._apply((function () {return this._apply(this.matchedInput, (function () {return this._repeat1(this.hexDigit);}));})));}),
(function () {return this._not(this.idChar);}),
(function () {return this._apply(this.token, 'number', (['hex']), (parseInt(text, 16)));}));}));
},

hexDigit: function () {
return this._apply((function () {return this._apply(this.char, (new Range('0', '9')), (new Range('a', 'f')), (new Range('A', 'F')));}));
},

string: function () {
var text;
return this._apply((function () {return this._concat((function () {return (text = this._apply((function () {return this._choice((function () {return this._apply(this.stringHelper, '\'');}),
(function () {return this._apply(this.stringHelper, '\"');}));})));}),
(function () {return this._apply(this.token, 'string', this.null, text);}));}));
},

stringHelper: function (quoteChar) {
var c, characters;
return this._apply((function () {return this._concat(quoteChar,
(function () {return (characters = this._apply((function () {return this._repeat((function () {return this._concat((function () {return this._not(quoteChar);}),
(function () {return (c = this._apply(this.stringChar));}));}));})));}),
quoteChar,
(function () {return ( characters.join('')
  );}));}));
},

stringChar: function () {
return this._apply((function () {return this._choice((function () {return this._concat('\\',
this.stringEscapeSequence);}),
(function () {return this._concat('\\',
this.newline,
(function () {return ( ''
    );}));}),
(function () {return this._concat((function () {return this._not(this.newline);}),
this.sourceChar);}));}));
},

stringEscapeSequence: function () {
var hs;
return this._apply((function () {return this._choice((function () {return this._concat('\'',
(function () {return ( '\''
    );}));}),
(function () {return this._concat('\"',
(function () {return ( '\"'
    );}));}),
(function () {return this._concat('\\',
(function () {return ( '\\'
    );}));}),
(function () {return this._concat('b',
(function () {return ( '\b'
    );}));}),
(function () {return this._concat('f',
(function () {return ( '\f'
    );}));}),
(function () {return this._concat('n',
(function () {return ( '\n'
    );}));}),
(function () {return this._concat('r',
(function () {return ( '\r'
    );}));}),
(function () {return this._concat('t',
(function () {return ( '\t'
    );}));}),
(function () {return this._concat('v',
(function () {return ( '\v'
    );}));}),
(function () {return this._concat('0',
(function () {return this._not(this.digit);}),
(function () {return ( '\0'
    );}));}),
(function () {return this._concat('x',
(function () {return (hs = this._apply((function () {return this._apply(this.repeat, this.hexDigit, (2), (2));})));}),
(function () {return ( String.fromCodepoint(hs.join(''))
    );}));}),
(function () {return this._concat('u',
(function () {return (hs = this._apply((function () {return this._apply(this.repeat, this.hexDigit, (4), (4));})));}),
(function () {return ( String.fromCodepoint(hs.join(''))
    );}));}),
(function () {return this._concat((function () {return this._not((function () {return this._choice(this.newline,
this.digit);}));}),
this.sourceChar);}));}));
},

regex: function () {
var pattern, options;
return this._apply((function () {return this._concat('/',
(function () {return (pattern = this._apply((function () {return this._apply(this.matchedInput, (function () {return this._concat((function () {return this._not('*');}),
this.regexChar,
(function () {return this._repeat(this.regexChar);}));}));})));}),
'/',
(function () {return (options = this._apply((function () {return this._apply(this.matchedInput, (function () {return this._repeat(this.idChar);}));})));}),
(function () {return this._apply(this.token, 'regex', this.null, (new RegExp(pattern, options)));}));}));
},

regexChar: function () {
return this._apply((function () {return this._choice((function () {return this._concat('\\',
(function () {return this._not(this.newline);}),
this.sourceChar);}),
this.regexCharacterClass,
(function () {return this._concat((function () {return this._not((function () {return this._choice('/',
this.newline);}));}),
this.sourceChar);}));}));
},

regexCharacterClass: function () {
return this._apply((function () {return this._concat('[',
this.regexCharacterClassChar,
']');}));
},

regexCharacterClassChar: function () {
return this._apply((function () {return this._choice((function () {return this._concat('\\',
(function () {return this._not(this.newline);}),
this.sourceChar);}),
(function () {return this._concat((function () {return this._not((function () {return this._choice(']',
this.newline);}));}),
this.sourceChar);}));}));
},

whitespace: function () {
return this._apply((function () {return this._repeat((function () {return this._choice(this.spaces,
this.newline,
this.comment);}));}));
},

spaces: function () {
return this._apply((function () {return this._concat((function () {return this._apply(this.char, ' \t\v\f\u00a0\u200c\u200d\ufeff');}),
(function () {return this._apply(this.token, 'spaces', (['whitespace']));}));}));
},

newline: function () {
return this._apply((function () {return this._concat((function () {return this._choice('\r\n',
(function () {return this._apply(this.char, '\n\r\u2028\u2029');}));}),
(function () {return this._apply(this.token, 'newline', (['whitespace']));}));}));
},

comment: function () {
return this._apply((function () {return this._concat((function () {return this._choice((function () {return this._concat('//',
(function () {return this._repeat((function () {return this._concat((function () {return this._not(this.newline);}),
this.sourceChar);}));}),
(function () {return this._choice(this.newline,
this.eof);}));}),
(function () {return this._concat('/*',
(function () {return this._repeat((function () {return this._concat((function () {return this._not('*/');}),
this.sourceChar);}));}),
'*/');}));}),
(function () {return this._apply(this.token, 'comment', (['whitespace']));}));}));
}

});
